### ISSUE TITLE
Command Registration

### ISSUE THREAD

**Issue by efraimbart** [IanMitchell/discord-trout#1]
Just wondering where the commands get registered to discord so discord knows what to offer.

**Comment by IanMitchell** [comment]
Hey! I have a script that does it manually - I didn't add it to this repo, but you can see how I had it here: https://ianmitchell.dev/blog/creating-a-discord-http-slash-command-bot-with-fastify

Towards the bottom there is a `register.js` file.

Holler if that doesn't give enough info or if you have more follow up questions! Happy to help

**Comment by efraimbart** [comment]
I think I see. Once you register them globally you don't need to register them individually for newly joining guilds?

Thanks for the help!

**Comment by IanMitchell** [comment]
Yeah, exactly! I use guild commands for local testing, and then register as global when I'm ready to launch
